stages:
  - test
  - build
  - lint
  - package
  - deploy

variables:
  PythonVersion: "3.8"
  DockerImageName: "todoapp"

python-ci:
  stage: test
  parallel:
    matrix:
      - PythonVersion: ["3.8", "3.9"]
      - OsType: ["ubuntu-latest", "windows-latest"]
  script:
    - apt-get update && apt-get install -y python${PythonVersion}
    - python -m pip install --upgrade pip
    - pip install coverage flake8
    - pip install -r requirements.txt
    - python manage.py test
    - coverage run --source='.' manage.py test
    - coverage report
    - flake8 . --show-source --statistics --exit-zero
    - flake8 . --exit-zero --max-complexity=6
  artifacts:
    paths:
      - ./
      - coverage.xml
    when: on_success
  only:
    - main

docker-ci:
  stage: build
  dependencies:
    - python-ci
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
    - docker build -t ${DOCKERHUB_USERNAME}/${DockerImageName}:${CI_COMMIT_SHA} ./src
    - docker push ${DOCKERHUB_USERNAME}/${DockerImageName}:${CI_COMMIT_SHA}
  only:
    - main

helm-ci:
  stage: package
  dependencies:
    - python-ci
  script:
    - apt-get update && apt-get install -y curl
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - helm lint ./todoapp/
    - helm template todoapp ./todoapp/ -f ./todoapp/values.yaml
    - helm package ./todoapp
  artifacts:
    paths:
      - ./*.tgz
  only:
    - main

deploy-helm-dev:
  stage: deploy
  dependencies:
    - helm-ci
    - docker-ci
  script:
    - helm upgrade --install todoapp ./todoapp --namespace development --set image.tag=${CI_COMMIT_SHA}
  environment:
    name: development
  only:
    - main

deploy-helm-stg:
  stage: deploy
  dependencies:
    - deploy-helm-dev
  script:
    - helm upgrade --install todoapp-staging ./todoapp --namespace staging -f ./todoapp/values/stg.yaml --set image.tag=${CI_COMMIT_SHA}
  environment:
    name: staging
  only:
    - main
